server:
  port: 8085

spring:
  config:
    activate:
      on-profile: development
url: jdbc:mysql://localhost:3306/db_dev
name: dev
password: dev
driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:file:/db/test
    username: test
    password: test
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
  h2:
    console.enabled: true

---
spring:
  config:
    activate:
      on-profile: production
url: jdbc:mysql://localhost:3306/db_prod
name: prod
password: prod
driver-class-name: com.mysql.cj.jdbc.Driver